permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: 文宝泉
  email: 198935110@163.com
  link: http://wenbaoquan.github.io/blog/
  # weibo: http://weibo.com/yansu0711
  github: http://github.com/wenbaoquan

# 站点信息
title: 文宝泉的博客
description: 文宝泉的博客
url: http://wenbaoquan.github.io/blog/
rss_url: /blog/pages/atom.xml

# avatar头像及Favicon
avatar: /blog/assets/img/clover.jpeg
favicon: /blog/assets/img/clover.jpeg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: wenbaoquan-zh