# Site settings
title: 文宝泉的个人博客
email: 605655201@qq.com
description: > # this means to ignore newlines until "baseurl:"
  文宝泉的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wenbaoquan.github.io/blog/" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter: ""
# weibo:    ID
github: wenbaoquan
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: http://o7emt00tc.bkt.clouddn.com/head_icon.png
favicon: http://o7emt00tc.bkt.clouddn.com/head_icon.png

# disqus 设置
disqus:
  shortname: wenbaoquan

# google analytics 设置
ga:
  id: UA-77963846-1
  url: http://wenbaoquan.github.io/blog/

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
